import { NextResponse } from "next/server";
import connectToDatabase from "../../../lib/mongodb";
import Order from "../../../../models/Order";
import User from "../../../../models/User";
import DailyStat from "../../../../models/DailyStat";

export const dynamic = "force-dynamic";

// 💥 ELITE ADMIN CACHE ENGINE & THREAD LOCK 💥
let adminSummaryCache: Record<string, { data: any, timestamp: number }> = {};
let isGeneratingCache = false; // Prevents Cache Stampede (Multiple Reload Crashes)
const SUMMARY_TTL = 2 * 60 * 1000; 

const extractServiceName = (msg: string) => {
    if (!msg) return "Other";
    const lowerMsg = msg.toLowerCase();
    if (lowerMsg.includes('whatsapp') || lowerMsg.includes(' wa ')) return 'WhatsApp';
    if (lowerMsg.includes('telegram') || lowerMsg.includes('t.me')) return 'Telegram';
    if (lowerMsg.includes('facebook') || lowerMsg.includes(' fb ')) return 'Facebook';
    if (lowerMsg.includes('instagram') || lowerMsg.includes(' ig ')) return 'Instagram';
    if (lowerMsg.includes('google') || /g-\d+/.test(lowerMsg) || lowerMsg.includes('gmail')) return 'Google';
    if (lowerMsg.includes('tiktok')) return 'TikTok';
    return "Other"; 
};

const getUTCDateString = (dateObj: any = new Date()) => {
  try { return new Date(dateObj).toISOString().split('T')[0]; } 
  catch (e) { return new Date().toISOString().split('T')[0]; }
};

export async function POST(req: Request) {
  try {
    await connectToDatabase();
    const { email, role, limitDays = 60 } = await req.json();

    if (role !== "admin") return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 403 });

    const cacheKey = `admin_summary_${limitDays}`;
    
    // 1. Return valid cache instantly
    if (adminSummaryCache[cacheKey] && (Date.now() - adminSummaryCache[cacheKey].timestamp < SUMMARY_TTL)) {
        return NextResponse.json(adminSummaryCache[cacheKey].data);
    }

    // 2. STAMPEDE PROTECTION: If cache is currently being generated by another admin request, return stale cache to avoid DB locking
    if (isGeneratingCache && adminSummaryCache[cacheKey]) {
        return NextResponse.json(adminSummaryCache[cacheKey].data);
    }

    // Lock the cache generation thread
    isGeneratingCache = true;

    try {
        const todayStrUTC = getUTCDateString(new Date());
        const isAllTime = limitDays === "all";

        let liveQueryDateStr = todayStrUTC;
        const currentUTCHour = new Date().getUTCHours();
        const currentUTCMin = new Date().getUTCMinutes();
        
        if (currentUTCHour === 0 && currentUTCMin <= 35) {
            const yesterdayDate = new Date();
            yesterdayDate.setUTCDate(yesterdayDate.getUTCDate() - 1);
            liveQueryDateStr = getUTCDateString(yesterdayDate);
        }
        
        const dailyStatQuery: any = { dateString: { $lt: liveQueryDateStr } };
        
        if (!isAllTime) {
            const limitNum = Number(limitDays) || 60;
            const pastDaysLimit = new Date();
            pastDaysLimit.setUTCDate(pastDaysLimit.getUTCDate() - limitNum);
            dailyStatQuery.dateString = { $gte: getUTCDateString(pastDaysLimit), $lt: liveQueryDateStr };
        }

        const orderQuery: any = { dateString: { $gte: liveQueryDateStr } }; 

        // FETCH DAILY STATS
        const dailyStatsAgg = await DailyStat.aggregate([
            { $match: dailyStatQuery },
            { $group: {
                _id: "$dateString",
                total: { $sum: { $ifNull: ["$totalNumbers", 0] } },
                allocation: { $sum: { $ifNull: ["$totalNumbers", 0] } },
                success: { $sum: { $ifNull: ["$successOTP", 0] } },
                failed: { $sum: { $cond: [{ $gt: ["$failedNumbers", null] }, "$failedNumbers", { $ifNull: ["$failed", 0] }] } },
                amount: { $sum: { $add: [{ $ifNull: ["$totalCost", 0] }, { $ifNull: ["$totalCommission", 0] }] } }
            }}
        ]);

        const groupedRawData: Record<string, any> = {};
        const todayAppCounts: Record<string, number> = {};
        const todayHourlyTraffic = [0, 0, 0, 0, 0, 0];

        dailyStatsAgg.forEach((ds: any) => {
            groupedRawData[ds._id] = { total: ds.total, allocation: ds.allocation, success: ds.success, failed: ds.failed, amount: ds.amount };
        });

        // 💥 MEMORY FIX: Using MongoDB Cursor Instead of Loading Array in RAM 💥
        const ordersCursor = Order.find(orderQuery)
            .select("status dateString createdAt updatedAt fullMessage orderCost orderCommission")
            .lean()
            .cursor(); // Stream records one by one to save CPU/RAM

        for await (const o of ordersCursor) {
           const currentStatus = (o.status || "").toUpperCase(); 
           const finalDateStr = o.dateString || getUTCDateString(o.createdAt);
           if (finalDateStr < liveQueryDateStr) continue; 

           if (!groupedRawData[finalDateStr]) groupedRawData[finalDateStr] = { total: 0, success: 0, failed: 0, amount: 0, allocation: 0 };
           groupedRawData[finalDateStr].total += 1; groupedRawData[finalDateStr].allocation += 1;

           if (currentStatus === "DONE" || currentStatus === "SUCCESS") {
              const msgArray = o.fullMessage ? o.fullMessage.split(/_\|\|_/) : [];
              let finalValidCount = 0;
              msgArray.forEach((m: string) => { if (m.trim() !== "" && !m.toLowerCase().includes("waiting")) finalValidCount += 1; });
              if (finalValidCount === 0) finalValidCount = 1;

              groupedRawData[finalDateStr].success += finalValidCount;
              // ADMIN COST: User Cost + Agent Commission
              groupedRawData[finalDateStr].amount += ((o.orderCost || 0) + (o.orderCommission || 0));

              if (finalDateStr === todayStrUTC) {
                  const hour = new Date(o.updatedAt || o.createdAt || new Date()).getUTCHours();
                  const bIdx = Math.floor(hour / 4);
                  if(bIdx >= 0 && bIdx <= 5) todayHourlyTraffic[bIdx] += finalValidCount;

                  let sName = extractServiceName(o.fullMessage);
                  if (!todayAppCounts[sName]) todayAppCounts[sName] = 0;
                  todayAppCounts[sName] += finalValidCount;
              }
           } else if (!["PENDING", "WAITING", "WAIT", "PROCESSING", "ACTIVE", "READY", ""].includes(currentStatus)) {
              groupedRawData[finalDateStr].failed += 1;
           }
        }

        const yesterdayDate = new Date(); yesterdayDate.setUTCDate(yesterdayDate.getUTCDate() - 1);
        const yesterdayStrUTC = getUTCDateString(yesterdayDate);

        const defaultData = { success: 0, amount: 0, total: 0, failed: 0 };
        const todayData = groupedRawData[todayStrUTC] || defaultData;
        const yesterdayData = groupedRawData[yesterdayStrUTC] || defaultData;

        const responsePayload = {
           success: true, groupedRawData, todayAppCounts, todayHourlyTraffic,
           userRate: 0, balance: 0, serverDate: todayStrUTC,
           todaySuccess: todayData.success, todaySpend: todayData.amount, 
           yesterdaySuccess: yesterdayData.success, yesterdaySpend: yesterdayData.amount
        };

        // Save to cache
        adminSummaryCache[cacheKey] = { data: responsePayload, timestamp: Date.now() };
        return NextResponse.json(responsePayload);

    } finally {
        // Always unlock the thread, even if an error occurs
        isGeneratingCache = false;
    }

  } catch (error) { 
      // Unlock just in case
      isGeneratingCache = false;
      return NextResponse.json({ success: false }); 
  }
}